
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/02_camera_testing.ipynb

# https://www.scivision.co/numpy-image-bgr-to-rgb/
def convert_bgr_to_rgb(x): return x[...,::-1]